var KEY_UP = 38;
var KEY_DOWN = 40;
var KEY_LEFT = 37;
var KEY_RIGHT = 39;
var KEY_SPACE = 32;
var KEY_PAUSE = 80;

var BEGIN_LIVES = 3;
var FIRE_MODE_NORMAL = 'normal';
var FIRE_MODE_TRIPLE = 'triple';

//sections
var GAME_OVER_WIDTH = 100;
var GAME_OVER_HEIGHT = 20;
var CADRE_X = 100;
var CADRE_Y = 100;
var CADRE_WIDTH = 500;
var CADRE_HEIGHT = 500;

//delais
var FREQUENCE_ASTEROID = 10;
var DELAI_TIR = 10;
var TEMPS_EXPLOSION = 10;
var TEMPS_EXPLOSION_VAISSEAU = 100;
var SPEED_UP_EVERY = 500;

//vaisseau
var POSITION_VAISSEAU_INIT_X = 100;
var POSITION_VAISSEAU_INIT_Y = 100;
var BEGIN_FIRE_MODE = FIRE_MODE_NORMAL;

//bonus
var BONUS = ["LIFE", "MISSILE_TRIPLE", "MISSILE_RAPIDE", "GOLD"];

var IMAGES_BONUS = [];
IMAGES_BONUS["LIFE"] = "life_resize.png";
IMAGES_BONUS["MISSILE_TRIPLE"] = "triple_fire_resize.png";
IMAGES_BONUS["MISSILE_RAPIDE"] = "speed_up_resize.png";
IMAGES_BONUS["GOLD"] = "iconGold_resize.png";

var PROBA_BONUS = [];
PROBA_BONUS["LIFE"] = 0.02;
PROBA_BONUS["MISSILE_TRIPLE"] = 0.03;
PROBA_BONUS["MISSILE_RAPIDE"] = 0.04;
PROBA_BONUS["GOLD"] = 0.07;

//asteroides
var ASTEROID = ["NORMAL", "GRIS", "STYLED"];

var PROBA_ASTEROID = [];
PROBA_ASTEROID["NORMAL"] = 0.1;
PROBA_ASTEROID["GRIS"] = 0.4;
PROBA_ASTEROID["STYLED"] = 0.05;

var IMAGES_ASTEROID = [];
IMAGES_ASTEROID["NORMAL"] = "asteroid.png";
IMAGES_ASTEROID["GRIS"] = "asteroid2.png";
IMAGES_ASTEROID["STYLED"] = "asteroid3_resize.png";

var POINTS_ASTEROID = [];
POINTS_ASTEROID["NORMAL"] = 50;
POINTS_ASTEROID["GRIS"] = 10;
POINTS_ASTEROID["STYLED"] = 200;

var FORCE_ASTEROID = [];
FORCE_ASTEROID["NORMAL"] = 1;
FORCE_ASTEROID["GRIS"] = 3;
FORCE_ASTEROID["STYLED"] = 5;

var IMAGES_ASTEROID_DETRUITE = [];
IMAGES_ASTEROID_DETRUITE["NORMAL"] = "asteroid_exp.png";
IMAGES_ASTEROID_DETRUITE["GRIS"] = "asteroid2_exp.png";
IMAGES_ASTEROID_DETRUITE["STYLED"] = "asteroid3_resize_exp.png";

//projectiles
var PROJECTILES = ["MID", "HAUT", "BAS"];

var keyListened = [KEY_UP,KEY_DOWN,KEY_LEFT,KEY_RIGHT,KEY_SPACE,KEY_PAUSE];